// File: kat_adc_wrapper.v
// Generated by MyHDL 0.7
// Date: Wed May  9 11:45:55 2012


`timescale 1ns/10ps

module kat_adc_wrapper (
    adc_clk_p,
    adc_clk_n,
    adc_sync_p,
    adc_sync_n,
    adc_overrange_p,
    adc_overrange_n,
    adc_rst,
    adc_powerdown,
    adc_di_d_p,
    adc_di_d_n,
    adc_di_p,
    adc_di_n,
    adc_dq_d_p,
    adc_dq_d_n,
    adc_dq_p,
    adc_dq_n,
    user_datai3,
    user_datai2,
    user_datai1,
    user_datai0,
    user_dataq3,
    user_dataq2,
    user_dataq1,
    user_dataq0,
    user_sync0,
    user_sync1,
    user_sync2,
    user_sync3,
    user_outofrange0,
    user_outofrange1,
    user_data_valid,
    mmcm_reset,
    ctrl_reset,
    ctrl_clk_in,
    ctrl_clk_out,
    ctrl_clk90_out,
    ctrl_clk180_out,
    ctrl_clk270_out,
    ctrl_mmcm_locked,
    mmcm_psclk,
    mmcm_psen,
    mmcm_psincdec,
    mmcm_psdone
);


input adc_clk_p;
input adc_clk_n;
input adc_sync_p;
input adc_sync_n;
input adc_overrange_p;
input adc_overrange_n;
input adc_rst;
input adc_powerdown;
input adc_di_d_p;
input adc_di_d_n;
input adc_di_p;
input adc_di_n;
input adc_dq_d_p;
input adc_dq_d_n;
input adc_dq_p;
input adc_dq_n;
input user_datai3;
input user_datai2;
input user_datai1;
input user_datai0;
input user_dataq3;
input user_dataq2;
input user_dataq1;
input user_dataq0;
input user_sync0;
input user_sync1;
input user_sync2;
input user_sync3;
input user_outofrange0;
input user_outofrange1;
input user_data_valid;
input mmcm_reset;
input ctrl_reset;
input ctrl_clk_in;
input ctrl_clk_out;
input ctrl_clk90_out;
input ctrl_clk180_out;
input ctrl_clk270_out;
input ctrl_mmcm_locked;
input mmcm_psclk;
input mmcm_psen;
input mmcm_psincdec;
input mmcm_psdone;







kat_adc_interface
#(
   .EXTRA_REG (1)
) kac_adc_interface_inst1 (
   .adc_clk_p         (adc_clk_p), 
   .adc_clk_n         (adc_clk_n),
   .adc_sync_p        (adc_sync_p),
   .adc_sync_n        (adc_sync_n),
   .adc_overrange_p   (adc_overrange_p),
   .adc_overrange_n   (adc_overrange_n),
   .adc_rst           (adc_rst),
   .adc_powerdown     (adc_powerdown),
   .adc_di_d_p        (adc_di_d_p),
   .adc_di_d_n        (adc_di_d_n),
   .adc_di_p          (adc_di_p),
   .adc_di_n          (adc_di_n),
   .adc_dq_d_p        (adc_dq_d_p),
   .adc_dq_d_n        (adc_dq_d_n),
   .adc_dq_p          (adc_dq_p),
   .adc_dq_n          (adc_dq_n),
                                        
   .user_datai3       (user_datai3),
   .user_datai2       (user_datai2),
   .user_datai1       (user_datai1),
   .user_datai0       (user_datai0),
   .user_dataq3       (user_dataq3),
   .user_dataq2       (user_dataq2),
   .user_dataq1       (user_dataq1),
   .user_dataq0       (user_dataq0),
   .user_sync0        (user_sync0),
   .user_sync1        (user_sync1),
   .user_sync2        (user_sync2),
   .user_sync3        (user_sync3),
   .user_outofrange0  (user_outofrange0),
   .user_outofrange1  (user_outofrange1),
   .user_data_valid   (user_data_valid),
                       
   .mmcm_reset        (mmcm_reset),
                       
   .ctrl_reset        (ctrl_reset),
   .ctrl_clk_in       (ctrl_clk_in),
   .ctrl_clk_out      (ctrl_clk_out),
   .ctrl_clk90_out    (ctrl_clk90_out),
   .ctrl_clk180_out   (ctrl_clk180_out),
   .ctrl_clk270_out   (ctrl_clk270_out),
   .ctrl_mmcm_locked  (ctrl_mmcm_locked),
                                        
   .mmcm_psclk        (mmcm_psclk),
   .mmcm_psen         (mmcm_psen),
   .mmcm_psincdec     (mmcm_psincdec),
   .mmcm_psdone       (mmcm_psdone)

);

endmodule
