// File: counter_wrapper.v
// Generated by MyHDL 0.8dev
// Date: Thu Nov 22 15:07:16 2012


`timescale 1ns/10ps

module counter_wrapper (
    clk,
    en,
    rst,
    out
);


input clk;
input en;
input rst;
output out;
wire out;







counter 
#(
   .ARCHITECTURE ("BEHAVIORAL"),
   .DATA_WIDTH   (8),
   .COUNT_FROM   (0),
   .COUNT_TO     (256),
   .STEP         (1)
) counter_cntr2 (
   .clk  (clk),
   .en   (en),
   .rst  (rst),
   .out  (out)
);

endmodule
